# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.45.0
        with:
          ruby-version: 2.6.5
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Install Dependencies
        run:
          sudo apt-get -yqq install libpq-dev

      - name: Build App
        run:
          gem install bundler

      - name: Install Gems
        run:
          bundle install --jobs 4 --retry 3

      - name: Prepare Database
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost/postgres"
          RAILS_ENV: test
        run:
          bundle exec rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost/postgres"
          RAILS_ENV: test
        run:
          bundle exec rails test
